# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads'
    app.mail_from: 'contact@JCHabitat.fr'

# Mentions légales
    company_name: 'JCHabitat & Services'
    company_legal_form: 'Entreprise individuelle au capital de 0 €'
    company_address: '34 rue de Mouvaux, 59200 Tourcoing'
    company_siret: '53363513200020'
    company_responsable: 'Jean-Charles Deledique'
    company_email: 'contact@jchabitat.fr'
    company_phone: '06 12 34 56 78'

    host_name: 'OVH SAS'
    host_address: '2 rue Kellermann, 59100 Roubaix, France'
    host_phone: '1007'

    insurance_company: 'MAAF Assurances'
    insurance_contract: '123456789'
    insurance_zone: 'France métropolitaine'

# Fin des mentions légales

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
